export interface AskingPriceInfo {
    // 매수호가가격1
    pbid1: string;
    // 매도호가가격1
    pask1: string;
    // 매수호가잔량1
    vbid1: string;
    // 매도호가잔량1
    vask1: string;
    // 매수호가대비1
    dbid1: string;
    // 매도호가대비1
    dask1: string;

    // 매수호가가격2
    pbid2: string;
    // 매도호가가격2
    pask2: string;
    // 매수호가잔량2
    vbid2: string;
    // 매도호가잔량2
    vask2: string;
    // 매수호가대비2
    dbid2: string;
    // 매도호가대비2
    dask2: string;

    // 매수호가가격3
    pbid3: string;
    // 매도호가가격3
    pask3: string;
    // 매수호가잔량3
    vbid3: string;
    // 매도호가잔량3
    vask3: string;
    // 매수호가대비3
    dbid3: string;
    // 매도호가대비3
    dask3: string;

    // 매수호가가격4
    pbid4: string;
    // 매도호가가격4
    pask4: string;
    // 매수호가잔량4
    vbid4: string;
    // 매도호가잔량4
    vask4: string;
    // 매수호가대비4
    dbid4: string;
    // 매도호가대비4
    dask4: string;

    // 매수호가가격5
    pbid5: string;
    // 매도호가가격5
    pask5: string;
    // 매수호가잔량5
    vbid5: string;
    // 매도호가잔량5
    vask5: string;
    // 매수호가대비5
    dbid5: string;
    // 매도호가대비5
    dask5: string;

    // 매수호가가격6
    pbid6: string;
    // 매도호가가격6
    pask6: string;
    // 매수호가잔량6
    vbid6: string;
    // 매도호가잔량6
    vask6: string;
    // 매수호가대비6
    dbid6: string;
    // 매도호가대비6
    dask6: string;

    // 매수호가가격7
    pbid7: string;
    // 매도호가가격7
    pask7: string;
    // 매수호가잔량7
    vbid7: string;
    // 매도호가잔량7
    vask7: string;
    // 매수호가대비7
    dbid7: string;
    // 매도호가대비7
    dask7: string;

    // 매수호가가격8
    pbid8: string;
    // 매도호가가격8
    pask8: string;
    // 매수호가잔량8
    vbid8: string;
    // 매도호가잔량8
    vask8: string;
    // 매수호가대비8
    dbid8: string;
    // 매도호가대비8
    dask8: string;

    // 매수호가가격9
    pbid9: string;
    // 매도호가가격9
    pask9: string;
    // 매수호가잔량9
    vbid9: string;
    // 매도호가잔량9
    vask9: string;
    // 매수호가대비9
    dbid9: string;
    // 매도호가대비9
    dask9: string;

    // 매수호가가격10
    pbid10: string;
    // 매도호가가격10
    pask10: string;
    // 매수호가잔량10
    vbid10: string;
    // 매도호가잔량10
    vask10: string;
    // 매수호가대비10
    dbid10: string;
    // 매도호가대비10
    dask10: string;
}